name: CI
on: [push, pull_request]
jobs:
  pre_job:
    name: Check duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "schedule", "workflow_dispatch"]'

  build:
    name: Test
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install
      - run: yarn lint
      - run: yarn flow
      - run: yarn test
      - run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
